Moj/otomi chart
redkubes/otomi-tasks pull request #35
Opened 2021-06-17 11:15 UTC by mojtabaimani

Adding a task to map a plain values.yaml from otomi chart to different value files and merge with current bootstrapped ones.

2021-06-17 11:34 UTC, j-zimnowoda requested changes
Nice work. Needs some unit tests.

2021-06-17 11:34 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +    console.log(e)
We should allow this task to fail if an exception occurs

2021-06-17 11:34 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +  } catch (e) {
Why do you catch it?

2021-06-17 11:34 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +function extractSecrets(schema: any, parentKey: string): any {
needs  unit tests

2021-06-17 11:34 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +function mergeValues(cat: string, valueObject, folder: string): void {
needs unit tests

2021-06-17 22:31 UTC, Morriz commented on src/tasks/otomi/otomi-chart.test.ts
> +    const x = extractSecrets(schema, 'root')
so leaving 'root' empty or undefined even would create '.pullSecret'? That could be another test, but I am not sure we need that. I am curious though

2021-06-17 22:33 UTC, Morriz requested changes
looking good...minor things

2021-06-17 22:33 UTC, Morriz commented on src/tasks/otomi/otomi-chart.ts
> +  const secretsJsonPath = extractSecrets(cleanSchema, 'root').map((str) => str.replace('root.', ''))
why the need to provide 'root'? Just write the function to make that param optional...

2021-06-18 14:48 UTC, j-zimnowoda requested changes
Impressive work. Few minor remarks

2021-06-18 14:48 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +main()
if (typeof require !== 'undefined' && require.main === module) {
  main()
}

So when you import this module the function is not executed

2021-06-18 14:48 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.test.ts
> +          [`x-secret`]: 'true',
'x-secret': 'true',

2021-06-18 14:48 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +async function main(): Promise<void> {
export default

2021-06-18 14:48 UTC, j-zimnowoda commented on src/tasks/otomi/otomi-chart.ts
> +export default function extractSecrets(schema: any, parentAddress?: string): Array<string> {
just export

2021-06-22 07:11 UTC, j-zimnowoda approved these changes

2021-06-23 12:11 UTC, Morriz commented
@j-zimnowoda why do you approve a non working solution?

2021-06-23 12:12 UTC, Morriz commented
And maybe we should start a PR in "draft" mode so it can't be approved @mojtabaimani

2021-06-28 07:15 UTC, j-zimnowoda commented
> @j-zimnowoda why do you approve a non working solution?

I saw it working and it passed my code review. Draft mode it is not a solution. We still need to invest in integration test framework, because it is not possible to test each PR manually.

2021-06-30 14:12 UTC, Morriz approved these changes

2021-06-30 14:12 UTC, merged