Keycloak task does not update config
redkubes/otomi-tasks pull request #42
Opened 2021-08-04 09:09 UTC by j-zimnowoda

Although we could see that task discovers existing configuration it has never update an existing configuration in some cases.
Read more: #41 

Instead of relaying on  getting HTTP 409 response for POST method and creating noise in keycloak log, I decided to check if resource exists and based on the result to either update or create the resource.

2021-08-04 13:19 UTC, Dunky13 approved these changes

2021-08-05 20:18 UTC, Morriz requested changes
I might be nitpicking here, but I just like to be thorough

2021-08-09 07:32 UTC, j-zimnowoda commented on src/tasks/keycloak/keycloak.ts
> +  if (allClients.some((el) => el.name === client.name)) {
Find also implies that first one matching is good enough .

After reading https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some and https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find I do not see a difference except `some` returns boolean and `find` returns integer.

2021-08-09 09:07 UTC, j-zimnowoda commented on src/tasks/keycloak/keycloak.ts
> +  idpMappers.map(async (idpMapper) => {
done

2021-08-09 09:08 UTC, j-zimnowoda commented on src/tasks/keycloak/keycloak.ts
> +  if (allClients.some((el) => el.name === client.name)) {
not do

2021-08-10 01:21 UTC, Morriz approved these changes

2021-08-10 01:21 UTC, merged