feat: create robot accounts with push creds for teams
redkubes/otomi-tasks pull request #77
Opened 2023-02-09 18:19 UTC by srodenhuis

Creating a Harbor robot account for each team with push credentials for team member to download

2023-02-22 12:38 UTC, dennisvankekem approved these changes
LGTM

2023-02-22 15:05 UTC, j-zimnowoda commented on src/tasks/harbor/harbor.ts
> +    throw new Error(
I am not sure if that is right wait of dealing with this error.
If I cannot create a robot account does it mean I cannot configure other parts of of Harbor ?

2023-02-22 15:06 UTC, j-zimnowoda commented on src/tasks/harbor/harbor.ts
> +      `RobotPullAccount already exists and should have been deleted beforehand. This happens when more than 100 robot accounts exist.`,
Is this a reported bug in harbor ?

2023-02-22 15:09 UTC, j-zimnowoda commented on src/tasks/harbor/harbor.ts
> +async function createTeamPushRobotAccount(projectName: string): Promise<any> {
Since it does not always create a secret can we rename this function to `ensureTeamPushRobotAccount` ?

2023-03-02 16:45 UTC, j-zimnowoda requested changes
There is too much duplicated code.

2023-03-06 14:43 UTC, j-zimnowoda approved these changes

2023-03-06 14:44 UTC, merged